default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: jzzsml
  password: <%= ENV['GEEKBRAINCOURSE_DATABASE_PASSWORD'] || Rails.application.credentials.dig(:postgres, :password, :development) %>
  timeout: 5000

development:
  <<: *default
  database: geek_brains_development

test:
  <<: *default
  database: geek_brains_test

production:
  <<: *default
  database: geek_brains_production




